name: qoo10jp-beauty-rank

on:
  schedule:
    - cron: "11 4 * * *" # 매일 KST 11:11 (UTC 04:11)
  workflow_dispatch:

concurrency:
  group: qoo10jp-beauty-rank
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    env:
      PYTHONUTF8: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      TZ: "Asia/Seoul"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          # Google API 의존성 보강용 packaging 추가
          pip install -U packaging
          # Playwright + Chromium 설치 (OS 의존성 포함)
          python -m playwright install --with-deps chromium
          pip freeze | grep -E 'packaging|google-api|google-auth|playwright' || true

      - name: Run crawler
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: |
          python app.py

      - name: Upload CSV artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: data-csv
          path: data/*.csv
          if-no-files-found: warn
          retention-days: 7
