name: Daiso Rank Crawler

on:
  workflow_dispatch:
  schedule:
    # 매일 KST 08:35 (UTC 23:35)
    - cron: "35 23 * * *"

env:
  PYTHONUTF8: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  TZ: "Asia/Seoul"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          # Google Drive 오류 방지용 packaging 보강
          pip install -U packaging
          # Playwright + Chromium 설치 (의존성 포함)
          python -m playwright install --with-deps chromium
          pip freeze | grep -E 'packaging|google-api|google-auth|playwright' || true

      - name: Run crawler
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: |
          python app.py

      - name: Upload CSV artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: data-csv
          path: data/*.csv
          if-no-files-found: warn
          retention-days: 7
